name: "When Opened"

on:
  pull_request_target:
    types:
    - opened

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    # NOTE: sync-labels due to https://github.com/actions/labeler/issues/112
    - name: Label PR
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: ''
    # Special action for a special day.
    - name: Special comment
      uses: pllim/action-special_pr_comment@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
